stages:
  - build
  - deploy

variables:
  NODE_VERSION: '14'

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - export PATH=/home/ubuntu/.nvm/versions/node/v18.16.0/bin:$PATH

lekstugan-server-build:
  stage: build
  image: node:$NODE_VERSION
  script:
    - cd lekstugan-server
    - npm install
    - npm run build
    - npm run lint
  artifacts:
    paths:
      - lekstugan-server/
<<<<<<< HEAD
=======
    expire_in: 1h
>>>>>>> 52828fd52d9cf1d0983a03358c2c33b25789f3f8

auth-service-build:
  stage: build
  image: node:$NODE_VERSION
  script:
    - cd auth-service
    - npm install
  artifacts:
    paths:
      - auth-service/
<<<<<<< HEAD
=======
    expire_in: 1h
>>>>>>> 52828fd52d9cf1d0983a03358c2c33b25789f3f8

lekstugan-client-build:
  stage: build
  image: node:$NODE_VERSION
  script:
    - cd lekstugan-client
    - npm install
    - npm run build
    - npm run lint
<<<<<<< HEAD
  artifacts:
    paths:
      - lekstugan-client/
=======
    - npm run test
  artifacts:
    paths:
      - lekstugan-client/
    expire_in: 1h
>>>>>>> 52828fd52d9cf1d0983a03358c2c33b25789f3f8

deploy:
  stage: deploy
  script:
    - scp -r lekstugan-server/dist $DEPLOY_SERVER_USER@$DEPLOY_SERVER_IP:/var/www/lekstugan/lekstugan-server
    - scp -r auth-service/* $DEPLOY_SERVER_USER@$DEPLOY_SERVER_IP:/var/www/lekstugan/auth-service
    - ssh $DEPLOY_SERVER_USER@$DEPLOY_SERVER_IP "cd /var/www/lekstugan/auth-service && npm install"
    - scp -r lekstugan-client/dist/* $DEPLOY_SERVER_USER@$DEPLOY_SERVER_IP:/var/www/lekstugan
    - ssh $DEPLOY_SERVER_USER@$DEPLOY_SERVER_IP "/home/ubuntu/.nvm/versions/node/v18.16.0/bin/pm2 restart all"
  environment:
    name: production
